# Ayden Jahola, 22406966 - Operating Systems Project 1
# ca216/myshell

myshell: myshell.c shell_commands.c utility.c
	mkdir -p ../bin
	gcc -Wall myshell.c shell_commands.c utility.c -o ../bin/myshell