# Ayden Jahola, 22406966 - Operating Systems Project 1
# ca216/myshell

CC=gcc
CFLAGS=-Wall

myshell: myshell.c shell_commands.c utility.c
	$(CC) $(CFLAGS) myshell.c shell_commands.c utility.c -o myshell
	